### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by bigardone** [mveytsman/heroicons_elixir#23]
👋🏼 Hi there! I'm trying to find the [refresh icon](https://heroicons.dev/?query=refresh), but it doesn't seem to exist in the library, or at least I can't find it. Is it possible to add it? Do you accept PRs?
Thanks in advance 🙌🏼

**Comment by mveytsman** [comment]
Hello!

`refresh` has been renamed to `arrow-path` and you can find it at [`Heroicons.arrow_path/1`](https://hexdocs.pm/heroicons/Heroicons.html#arrow_path/1).

For what it's worth, http://heroicons.com/ is a better up-to-date resource for Heroicons. I find that https://heroicons.dev is out of date...

**Comment by bigardone** [comment]
Awesome! Thank you so much 🙌
