### ISSUE TITLE
This package prevents using Phoenix Live View 0.19

### ISSUE THREAD

**Issue by nickjj** [mveytsman/heroicons_elixir#24]
The `mix.exs` file has:

https://github.com/mveytsman/heroicons_elixir/blob/3b4aa3b2a6b88eb7f5b56ee03b6d1d6987dcfd35/mix.exs#L30

If you try to use Live View 0.19 and this package you get this error:

```
#0 2.180 Because "your app" depends on "heroicons 0.5.2" which depends on "phoenix_live_view ~> 0.18.2", "phoenix_live_view ~> 0.18.2" is required.
#0 2.180 So, because "your app" depends on "phoenix_live_view 0.19.0", version solving failed.
```

**Comment by ghenry** [comment]
I was just about to report this too!

**Comment by ghenry** [comment]
Anyone tried just updating mix.exs?

**Comment by nathanmalishev** [comment]
I've sent in a PR here - https://github.com/mveytsman/heroicons_elixir/pull/25 @ghenry

**Comment by mveytsman** [comment]
Thanks Nathan I will review this today

**Comment by ghenry** [comment]
> I've sent in a PR here - #25 @ghenry

Amazing. Thank you for taking time to do this for everyone. Much appreciated!

**Comment by mveytsman** [comment]
[0.5.3](https://hex.pm/packages/heroicons/0.5.3) is on hex.pm!

Thanks for your help everyon!!
