### ISSUE TITLE
Error when rendering icons without any style modifiers

### ISSUE THREAD

**Issue by sevenseacat** [mveytsman/heroicons_elixir#35]
The following code now raises an error with the latest version of `heroicons` - 

```
<Heroicons.arrow_right_on_rectangle class="w-6 h-6 mr-2 inline" />
```

The function component `arrow_right_on_rectangle` does not define a `micro` attribute, so the `svg` function has no `micro` attribute in the assigns and falls through to the error clause.

**Comment by mveytsman** [comment]
Thanks for the report @sevenseacat, I'll be pushing a new version to fix this!

**Comment by mveytsman** [comment]
0.5.5 released, and 0.5.4 has been retired!

**Comment by sevenseacat** [comment]
Thanks for the super-quick fix, it works great :D

**Comment by krns** [comment]
Thanks guys! I was just about to create an issue 😀 awesome speed!
