### ISSUE TITLE
Possibly bug with error "expected either mini or solid, but got both." 

### ISSUE THREAD

**Issue by luigi-discoup** [mveytsman/heroicons_elixir#37]
The [arrow_right_on_rectangle](https://github.com/mveytsman/heroicons_elixir/blob/main/lib/heroicons.ex#L13116) icon is missing `micro` attribute and this leads to an `expected either mini or solid, but got both.` error rise.

**Comment by luigi-discoup** [comment]
It seems that the following icons are missing the `micro` attribute:

1. `arrow_right_on_rectangle`
2. `plus_small`
3. `minus_small`
4. `arrow_small_left`
5. `arrow_small_up`
6. `arrow_small_down`
7. `arrow_small_right`
8. `arrow_left_on_rectangle`

**Comment by mveytsman** [comment]
Hi @luigi-discoup this is a dupe of #35 - I pushed a new version 0.5.5 and retired the broken one. Can you upgrade and confirm it's fixed

**Comment by luigi-discoup** [comment]
Hi @mveytsman, sorry for the dupe, #35 was already closed when I open this. I've upgraded and it is fixed. Thank you
