### ISSUE TITLE
Mix script to update SVGs from Github

### ISSUE THREAD

**Issue by greven** [mveytsman/heroicons_elixir#6]
Hey, first and foremost thanks for this.
I was using heroicons on my project but extracing the SVGs into a file and created a Macro to do the in-lining, but using the new Pheonix components is much better DX, so thanks for this package. :)

I was thinking it would be cool to have a way to update the SVGs (in priv) easily so it's easier to keep up with new releases?
Took some code from the Phoenix Tailwind and sass installers for the downloading part. After the unziping of the archive, we just copy the optimized directory contents to the `priv` folder.
Wrapped it into a heroicons.update Mix task.

If you think this is useful, I can open a PR.

My commit is here: https://github.com/greven/heroicons_elixir/commit/8b890e34bd61ffe3ee9f4151f89e1e15c80df781

**Comment by greven** [comment]
Right now this only runs through a mix task, so only useful for publishing new versions.
We can maybe build on this to update the version / icons when building the dependency.

**Comment by mveytsman** [comment]
❤️ thanks for this!

I like the idea of downloading the heroicons during build, fixed to a version. What do you think of following the pattern in https://github.com/phoenixframework/esbuild to do that?

**Comment by greven** [comment]
> ❤️ thanks for this!
> 
> I like the idea of downloading the heroicons during build, fixed to a version. What do you think of following the pattern in https://github.com/phoenixframework/esbuild to do that?

Yep, think that is a great idea. :)
Why did I think about implementing this? Because they are releasing a new version of the icons (overhaul) and thought about making it simpler to update.
Thanks, I'll work on the commit and submit a PR for your review. :)

👍

**Comment by greven** [comment]
@mveytsman I've been working a bit on this this weekend to create the PR (sorry for the delay, lots of work recently).

I have some doubts about how to tackle this.
Right now I have a mix task to update the icons fixed to a version, useful either for packaging a new release.
This is a bit different than :esbuild since in :esbuild you can also run `mix esbuild.install` to install it and/or you need to add esbuild to phoenix watchers (in development) in order to call install_and_run (` esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}`.

Now... we don't need to have an application running, do we? So our use case is a bit different, we can just have the update mix task as :esbuild has the install mix task.

In order to download the version configured by the user at build time to override the files packaged in /priv, is that even possible? Maybe some sort of post install hook?, I don't know a way to do that other than to override `mix deps.get` in the mix aliases but that is userland, anyway.

So my conclusion for now at least is we can do with just the heroicons.update mix Task. Any ideas?

Thanks!

**Comment by mveytsman** [comment]
@greven I see what you're saying. Can you make a PR and I'll review it ?

**Comment by greven** [comment]
Completely forgot about this, remembered now that Heroicons 2 is getting released. I'm on holiday away from the computer but when I get back, start of the next week I'm creating the PR. There is a new type of icons now too, Mini.

**Comment by greven** [comment]
@mveytsman Think we can close this issue, right? Great job on the cache by the way, that's a nice idea for runtime generation! 👍
